port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 114.114.114.114
  - 8.8.8.8
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - https://dns.hinet.net/dns-query
  - tls://8.8.4.4:853
  - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
profile:
  store-selected: true
skip-auth-prefixes:
- 127.0.0.1/8
- "::1/128"
- 10.0.0.0/8
- 192.168.0.0/16
- 172.16.0.0/12
